# Generated by Django 5.2.11 on 2026-03-10 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_autor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name': 'autor', 'verbose_name_plural': 'autores'},
        ),
    ]
